contactapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("contacts.urls")),
    path("", include("user.urls")),
    path("api/contacts/", include("contacts.api.urls")),
]

contacts/api/urls.py
from django.urls import path
from .view import ContactsRudView, ContactsLCView


app_name = "contacts"
urlpatterns = [
    path("<int:pk>", ContactsRudView.as_view(), name="post-rud"),
    path("", ContactsLCView.as_view(), name="post-lc"),
]

contacts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    ContactListView,
    ContactDetailView,
    ContactCreateView,
    ContactUpdateView,
    ContactDeleteView,
)

app_name = "contacts"

urlpatterns = [
    path(
        "contacts/<int:pk>",
        login_required(ContactDetailView.as_view()),
        name="detail-view",
    ),
    path("add/", login_required(ContactCreateView.as_view()), name="add-view"),
    path("contacts/", login_required(ContactListView.as_view()), name="list-view"),
    path(
        "contacts/<int:pk>/update",
        login_required(ContactUpdateView.as_view()),
        name="update-view",
    ),
    path(
        "contacts/<int:pk>/delete",
        login_required(ContactDeleteView.as_view()),
        name="delete-view",
    ),
]

user/urls.py
from django.urls import path
from .views import SignUpView
from django.contrib.auth.views import LoginView, LogoutView


app_name = "user"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="register"),
    path("", LoginView.as_view(template_name="user/login.html"), name="login"),
    path(
        "logout/", LogoutView.as_view(template_name="user/logout.html"), name="logout"
    ),
]

contacts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Contacts(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    contactNumber = models.CharField(max_length=20)
    email = models.EmailField(max_length=254)
    address = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def get_absolute_url(self):
        return reverse("contacts:detail-view", kwargs={"pk": self.id})

    def get_update_url(self):
        return reverse("contacts:update-view", kwargs={"pk": self.id})

    def get_delete_url(self):
        return reverse("contacts:delete-view", kwargs={"pk": self.id})

    def __str__(self):
        return f"{self.firstName}"

user/models.py
from django.db import models

# Create your models here.

contacts/forms.py
from django import forms
from .models import Contacts


class AddContactForm(forms.ModelForm):
    class Meta:
        model = Contacts
        fields = ["firstName", "lastName", "contactNumber", "email", "address"]

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "first_name"]

contacts/views.py
from django.shortcuts import reverse, redirect
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
)
from contacts.forms import AddContactForm
from .models import Contacts
from django.urls import reverse_lazy


class ContactListView(ListView):
    paginate_by = 5
    model = Contacts
    template_name = "contacts/listview.html"
    ordering = ["firstName"]

    def get_queryset(self):
        searched = self.request.GET.get("searched")
        if searched:
            return Contacts.objects.filter(
                user=self.request.user, firstName__icontains=searched
            )
        return Contacts.objects.filter(user=self.request.user)


class ContactCreateView(CreateView):
    template_name = "contacts/add.html"
    form_class = AddContactForm
    success_url = reverse_lazy("contacts:list-view")

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
        return redirect(reverse("contacts:list-view"))


class ContactUpdateView(UpdateView):
    form_class = AddContactForm
    queryset = Contacts.objects.all()
    template_name = "contacts/update.html"

    def get_success_url(self):
        pk = self.kwargs.get("pk")

        return reverse("contacts:detail-view", kwargs={"pk": pk})


class ContactDetailView(DetailView):
    model = Contacts
    template_name = "contacts/detail.html"
    context_object_name = "obj"


class ContactDeleteView(DeleteView):
    model = Contacts
    context_object_name = "obj"
    template_name = "contacts/delete.html"
    success_url = reverse_lazy("contacts:list-view")

user/views.py
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from .forms import UserRegisterForm
from django.views.generic.edit import CreateView


class SignUpView(SuccessMessageMixin, CreateView):
    template_name = "user/register.html"
    success_url = reverse_lazy("user:login")
    form_class = UserRegisterForm
    success_message = (
        "Your profile was created successfully, Log in now to enter Contact App"
    )

templates/contacts/add.html
{% extends 'contacts/base.html' %}
{% block content %}
<form  method ='POST'>{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save">
</form>
<a href="{%url 'contacts:list-view'%} "> Go To List</a>
{% endblock content %}

templates/contacts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Contacts</title>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div>
            {{message}}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
</body>
</html>
            
        
    
    

templates/contacts/delete.html
{% extends 'contacts/base.html' %}
{% block content %}
<form  method ='POST'>{% csrf_token %}
    <h1>Do you want to delete contact "{{obj.firstName}}"?</h1>
    <input type="submit" value="Yes"> 
        <a href="{% url 'contacts:detail-view' obj.id %}"> Cancel</a>
</form>
{% endblock content %}

templates/contacts/detail.html
{% extends "contacts/base.html" %}

{% block content %}
<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
        
        <div class="navbar-nav">
            
            <a class="nav-item nav-link" href="{{obj.get_update_url}}">Update</a>
            <a class="nav-item nav-link" href="{{obj.get_delete_url}}">Delete</a>
            
        </div>
        
    </div>
</nav>
    {{obj.firstName}} {{obj.lastName}}
    <br>
    {{obj.contactNumber}}
    <br>
    {{obj.email}}
    <br>
    {{obj.address}}
    <br>
    <div>
        <a href="{% url "contacts:list-view"%}">All Contacts</a>
    </div>
{% endblock content %}
    

templates/contacts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>LOADING...</title>
</head>
<body>
    <h1><a href="{%url 'contacts:list-view'%}">Load Contact App</a></h1>
</body>
</html>

templates/contacts/listview.html
{% extends "contacts/base.html" %}
{% block content %}
<h1>Welcome {{user.first_name}}</h1>
<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
        
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'contacts:add-view' %}">Add Contact</a>
        </div>
        
    </div>
    <form>
        <input type="search" placeholder ='Search By Name' name= 'searched'>
        <button type="submit">Search</button>
    </form>
</nav>
    {% for obj in page_obj%}
        <p> 
         <a href="{{obj.get_absolute_url}}"> {{obj.firstName}} {{obj.contactNumber}}  </a>
        </p>
        
        <br>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
<nav>
<a href="{% url "user:logout"%}">Logout</a>
</nav>
{% endblock content %} 
    

templates/contacts/search.html
{% extends 'contacts/base.html' %}
{% block content %}
<center>   
    {% if searched %}
        <h1>
        You searched for {{searched}}
        </h1>
        <br>
        {% for con in contact %}
            {{con.firstName}}
            {{con.lastName}}
            {{con.contactNumber}}
            {{con.email}}
            {{con.address}}
            <br>
        {% endfor %}
    {% else %} 
        <h1>
        You did not search for anything !        
        </h1>        
    {% endif %}
</center>
{% endblock content %}

templates/contacts/update.html
{% extends 'contacts/base.html' %}
{% block content %}
<form  method ='POST'>{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save">
</form>
<a href="{% url 'contacts:list-view'%}">Go Back to Contact List</a>
{% endblock content %}

templates/user/login.html
{% extends 'contacts/base.html' %}
{% block content %}
<div>
    <form  method ='POST'>
        {% csrf_token %}
        <fieldset>
            <legend>Log in Now</legend>
            {{form.as_p}}
        </fieldset>
        <div>
            <button type="submit">Login</button>
        </div>
    </form>
    <div>
        <small>
            Do you need a account? <a href="{% url 'user:register' %}">Sign Up</a>
        </small>
    
    
    </div>
   




</div>

{% endblock content %}

templates/user/logout.html
{% extends 'contacts/base.html' %}
{% block content %}
    <h1>You have been logged out</h1>
    <div>
        <small>
            Log in again? <a href="{% url 'user:login' %}">Log In</a>
            <br>
            Need an account?<a href="{% url "user:register"%}">Sign Up</a>
        </small>

    
    </div>
   





{% endblock content %}

templates/user/register.html
{% extends 'contacts/base.html' %}
{% block content %}
<div>
    <form  method ='POST'>
        {% csrf_token %}
        <fieldset>
            <legend>Sign Up Now</legend>
            {{form.as_p}}
        </fieldset>
        <div>
            <button type="submit">Sign Up</button>
        </div>
    </form>
    <div>
        <small>
            {% comment %} Already hava an account? <a href="{% url 'login'  %}">Log In</a> {% endcomment %}
            Already hava an account? <a href="{% url 'user:login' %}">Log In</a>
        </small>
    
    
    </div>
   




</div>

{% endblock content %}